#!/bin/bash
# Launch script for NOVA
# Auto-generated by Nova Profile Migration System

echo "🚀 Launching NOVA with SS Launcher V3"
echo "📁 Working from profile directory: $(pwd)"

# Set profile directory as working directory
cd "/nfs/novas/profiles/nova"

# Launch with session restoration
/nfs/projects/nova-unified-ecosystem/core-infrastructure/ss-launcher/bin/ss-launcher-v3 \
    nova \
    --memory-mode=continue \
    --session-restore=true \
    --profile=/nfs/novas/profiles/nova

echo "✅ NOVA session completed"
