#!/bin/bash
# Launch script for AIDEN
# Auto-generated by Nova Profile Migration System

echo "🚀 Launching AIDEN with SS Launcher V3"
echo "📁 Working from profile directory: $(pwd)"

# Set profile directory as working directory
cd "/nfs/novas/profiles/aiden"

# Launch with session restoration
/nfs/projects/nova-unified-ecosystem/core-infrastructure/ss-launcher/bin/ss-launcher-v3 \
    aiden \
    --memory-mode=continue \
    --session-restore=true \
    --profile=/nfs/novas/profiles/aiden

echo "✅ AIDEN session completed"
